DROP TABLE IF EXISTS APP_USER;
CREATE TABLE APP_USER(
id INT AUTO_INCREMENT PRIMARY KEY,
pseudo VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS SERIE;
CREATE TABLE SERIE(
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(20) NOT NULL,
description VARCHAR(100),
lastUpdatedDate VARCHAR(20) NOT NULL

);

DROP TABLE IF EXISTS USER_SERIE;
CREATE TABLE USER_SERIE(
id INT AUTO_INCREMENT PRIMARY KEY,
privilege VARCHAR(20) NOT NULL,
owner BOOLEAN NOT NULL,
id_user INT,
id_serie INT,
FOREIGN KEY(id_user) REFERENCES APP_USER(id),
FOREIGN KEY(id_serie) REFERENCES SERIE(id)

);

DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT(
id INT AUTO_INCREMENT PRIMARY KEY,
event_date VARCHAR(20) NOT NULL,
event_value INT NOT NULL,
comment VARCHAR(50),
lastupdateddate VARCHAR(20) NOT NULL,
id_serie INT,
FOREIGN KEY(id_serie) REFERENCES SERIE(id)

);

DROP TABLE IF EXISTS TAG;
CREATE TABLE TAG(
label VARCHAR(20) PRIMARY KEY,
id_event INT,
FOREIGN KEY(id_event) REFERENCES EVENT(id)
);